### ISSUE TITLE
Should we run Pore-C pipeline to generate the virtual digest for annopy python script?

### ISSUE THREAD

**Issue by callumparr** [zhengdafangyuan/HiPore-C#3]
I am running some of our old Pore-C data on iPSCs with your hi-pore-c pipeline. We also used DpnII as originally recommended by Nanopore. 

As this file `genome_digest_frag="./Scripts/DpnII_GRCh38.vd.fragments.csv"` is not included in the repository I am guessing that we should generate that file ourselves with the pore-c pipeline from Nanopore? 

To confirm you used the GRCh38 no analysis set for reference? As I may have a virtual digest of hg38.fa with DpnII. I guess the no_analysis_set would be a subset of hg38.fa anyway.

**Comment by zhengdafangyuan** [comment]
Sorry for the late reply. Primary assembly chromosomes(chr1 ~ chr22, chrX, chrY) frome GRCh38_no_alt_analysis_set_GCA_000001405.15 were selected and merged ito GCA_000001405.15_GRCh38_major_chr.fa to used as refference.

The DpnII digetsion fragment file could generate by cooler using:
` 
cooler digest -o hg38_DpnII_digetstion_fragment.bed hg38.chromosomes.size GCA_000001405.15_GRCh38_major_chr.fa DpnII

echo "chrom,start,end,fragment_length,fragment_id" > DpnII_GRCh38.vd.fragments.csv  #DpnII_GRCh38.vd.fragments.csv with columns [chrom, start, end, fragment_length, fragment_id]
awk -v OFS="," '{pirnt $1,$2,$3,$3-$2,NR}' hg38_DpnII_digetstion_fragment.bed >> DpnII_GRCh38.vd.fragments.csv
`

**Comment by callumparr** [comment]
Thank you for the reply, works great.

**Comment by callumparr** [comment]
As I ran the alignment bash script with all the patches in the no_analysis_set (i.e. including unplaced patches) I was wondering whether this may have a downstream effect on the annotation python script but seems to be OK as it lists the fragment alignments in the Read_align_Fragment_RvdF.csv

**Comment by zhengdafangyuan** [comment]
The alignment would be more comprehensive, but the unplaced patches fragments seem to be of little use for subsequent analysis.

**Comment by callumparr** [comment]
Yes, you are totally right. It doesn't make much sense to work out the contacts where the loci cannot be placed in relation to other loci. 

I will just run the alignment again with the reference subset. 

TY
