### ISSUE TITLE
Did you see large no. of pores as saturated

### ISSUE THREAD

**Issue by callumparr** [zhengdafangyuan/HiPore-C#6]
![image](https://user-images.githubusercontent.com/41637575/194340369-7f8b790e-ca9f-4919-b9ac-919822c26425.png)

I followed the decrosslinking version 1 protocol, that is several treatments with proteinase K.

I did notice that the drop off in active pores was less steep than Pore-C protocol there was also a large no. of saturated pores. I have not seen this before. Usually blocked pores resulting from Pore-C revert to unavailable status.

I was wondering if perhaps there is some carry-over of some contaminatnt. 

In the paper do you break down the pore status over time?

**Comment by zhengdafangyuan** [comment]
Indeed, after multiple rounds of proteinase K treatments, there may still be small amount of residual peptides. But in our results,  saturated pores do not appear to such high ratio.  And this may be related to the hydrolysis efficiency of proteaseK, you can try to extend the reaction time of each round.

![image](https://user-images.githubusercontent.com/20550608/195233759-f3fb094e-b5bf-4afa-91e6-e7914236c1aa.png)

**Comment by callumparr** [comment]
I received some Pronase this week so next time I try I will go for version 2 of decrosslinking.
