### ISSUE TITLE
Generate_Pairwise_contact_juicematrix.py generates files where some lines have multiple readIDs on a line

### ISSUE THREAD

**Issue by callumparr** [zhengdafangyuan/HiPore-C#7]
I noticed that the no. of adjacent and non adjacent contacts as determined by no. of lines in the two files was not adding up to what was in the stat file. 

Then when combining the adjacent and non-adjacent files into one juice matrix file and creating .cool and .hic files I noticed that some lines had more than one contact per line. I am unsure where this error arises from but here is an examples :

```
❯ grep "606c9f29f0-41b8-4095-b377-c8004547876c" Nonadj_contact_matrix.txt
6c9f1eb0-3cf5-4582-900e-9cdaf24185c7 -1 chr5 127278614 0 0 chr5 79127038 1 60 606c9f29f0-41b8-4095-b377-c8004547876c -1 chr14 31775509 0 -1 chr14 31902435 1 60 60
❯ grep "606c9f29f0-41b8-4095-b377-c8004547876c" Adj_contact_matrix.txt
6c9f2255-f689-4179-8a25-0bc066a55ca3 0 chr10 41899280 0 0 chr4 49095789 1 60 606c9f29f0-41b8-4095-b377-c8004547876c -1 chr14 31775509 0 -1 chr14 31779001 1 60 60
```

I found this readID because it was producing error when trying to generate .hic file.

**Comment by callumparr** [comment]
From testing this only seems to happen when using the `-s 1` option, that is separating adjacent and non-adjacent contacts into separate files.

**Comment by zhengdafangyuan** [comment]
This error is due to the missing line break at  the last line of each output to the  matrix.txt.  I fixed the bud in the new upload Generate_Pairwise_contact_juicematrix.py .

**Comment by callumparr** [comment]
Thank you very much!
